apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-mysql-pv01
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /data/container_data/mysql_mamster/pv1
    server: 172.23.5.86
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-master-pvc01
  labels:
    app: mysql-master
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
