apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mysql-m-node
  labels:
    name: mysql-m-node
spec:
  serviceName: "mysql-m-service"
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-m-node
    spec:
      terminationGracePeriodSeconds: 10
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - mysql
              topologyKey: kubernetes.io/hostname
      containers:
      - name: mysql-master
        image: 172.23.5.1:8806/huangming/mysql-master:5.7.23
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-root-pass
                key: password
          - name: MYSQL_REPLICATION_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-repl-pass
                key: password
          - name: MYSQL_REPLICATION_USER
            value: "repl"
        volumeMounts:
        - name: mysql-master-vol
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-master-vol
        persistentVolumeClaim:
          claimName: mysql-master-pvc01
